name: Build Bootloader 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./firmware/bootloader-firmware

    steps:
    - uses: actions/checkout@v2
    
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '9-2019-q4' # The arm-none-eabi-gcc release to use.
      
    - name: Compile
      run: make

    - name: Move to build
      run: mv main.bin ./build/
      
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: 'Github action build'
        add: 'main.bin --force'
        cwd: './firmware/bootloader-firmware/build/'

